//-------------------------------------------------------
// Autogenerated from 'diescraper_random_radio.vmf'
//-------------------------------------------------------
DiescraperRandomRadio <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.toolbox,
			EntityGroup.SpawnTables.random_radio_prop1,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.random_radio_prop1,
			EntityGroup.SpawnTables.button_random_radio,
			EntityGroup.SpawnTables.toolbox,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			toolbox = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "121 202 0"
					glowrange = "240"
					glowstate = "3"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/radio_box.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "toolbox"
					origin = Vector( 0, 0, 0 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfDisable0-1"
							cmd2 = "!selfEnable90-1"
						}
					}
				}
			}
			button_random_radio = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "toolbox"
					origin = Vector( -19, -3, 9 )
					targetname = "button_random_radio"
					vscripts = "usetargets/diescraper_random_radio"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfRunScriptCodeg_ModeScript.SessionState.SpawnedItems.extend(g_ModeScript.SpawnRandomItems(SessionState.NumSpawnsAtOnce + 5));0-1"
							cmd2 = "!selfRunScriptCodeg_ModeScript.SessionState.RemoveRandomItemsNext <- false;0-1"
						}
					}
				}
			}
			random_radio_prop1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/tier2_guns_trophy.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					targetname = "random_radio_prop1"
					origin = Vector( 0, 0, 9 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // DiescraperRandomRadio

RegisterEntityGroup( "DiescraperRandomRadio", DiescraperRandomRadio )
