//-------------------------------------------------------
// Autogenerated from 'diescraper_weathermachine.vmf'
//-------------------------------------------------------
DiescraperWeathermachine <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.weathermachine_pump,
			EntityGroup.SpawnTables.toolbox,
			EntityGroup.SpawnTables.weathermachine_cooler,
			EntityGroup.SpawnTables.weathermachine_fan,
			EntityGroup.SpawnTables.weathermachine_fanbase,
			EntityGroup.SpawnTables.weathermachine_block,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.weathermachine_steam1,
			EntityGroup.SpawnTables.weathermachine_fan,
			EntityGroup.SpawnTables.button_weathermachine,
			EntityGroup.SpawnTables.weathermachine_relay,
			EntityGroup.SpawnTables.weathermachine_fanbase,
			EntityGroup.SpawnTables.weathermachine_motor,
			EntityGroup.SpawnTables.weathermachine_pump,
			EntityGroup.SpawnTables.weathermachine_shake,
			EntityGroup.SpawnTables.weathermachine_stopsound,
			EntityGroup.SpawnTables.toolbox,
			EntityGroup.SpawnTables.weathermachine_cooler,
			EntityGroup.SpawnTables.weathermachine_steam2,
			EntityGroup.SpawnTables.weathermachine_block,
			EntityGroup.SpawnTables.weathermachine_startsound,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			weathermachine_pump = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_equipment/diesel_pump2.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "weathermachine_pump"
					origin = Vector( 0, -7.31708, 0 )
				}
			}
			toolbox = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "121 202 0"
					glowrange = "240"
					glowstate = "3"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/buildable_button.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "toolbox"
					origin = Vector( -46, -25.3171, 47 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfDisable0-1"
							cmd2 = "!selfEnable90-1"
						}
					}
				}
			}
			button_weathermachine = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "toolbox"
					origin = Vector( -64.02, -39.75, 9 )
					targetname = "button_weathermachine"
					vscripts = "usetargets/diescraper_weathermachine"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "weathermachine_relayTrigger0-1"
						}
					}
				}
			}
			weathermachine_shake = 
			{
				SpawnInfo =
				{
					classname = "env_shake"
					amplitude = "2"
					duration = "7"
					frequency = "100"
					radius = "500"
					spawnflags = "0"
					targetname = "weathermachine_shake"
					origin = Vector( -66.5472, -14.1833, 9 )
				}
			}
			weathermachine_startsound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "dlc.Generator_start_run_loop"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "weathermachine_pump"
					spawnflags = "16"
					targetname = "weathermachine_startsound"
					origin = Vector( -64.0034, 15.3184, 9 )
				}
			}
			weathermachine_stopsound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "dlc.Generator_stop"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "weathermachine_pump"
					spawnflags = "16"
					targetname = "weathermachine_stopsound"
					origin = Vector( -81, 15.6829, 9 )
				}
			}
			weathermachine_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "weathermachine_relay"
					origin = Vector( -42.4056, 39.7471, 9 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "weathermachine_motorTurnOn1-1"
							cmd2 = "weathermachine_motorTurnOff85-1"
							cmd3 = "weathermachine_shakeStartShake0-1"
							cmd4 = "helipad_windtimerDisable0-1"
							cmd5 = "helipad_windtimerEnable89-1"
							cmd6 = "weathermachine_stopsoundPlaySound83-1"
							cmd7 = "weathermachine_startsoundPlaySound0-1"
							cmd8 = "weathermachine_startsoundStopSound83-1"
							cmd9 = "weathermachine_steam1Start1.5-1"
							cmd10 = "weathermachine_steam2Start2.9-1"
							cmd11 = "weathermachine_steam2Stop83.5-1"
							cmd12 = "weathermachine_steam1Stop87-1"
							cmd13 = "helipad_windStopSound0-1"
							cmd14 = "helipad_windPlaySound87-1"
						}
					}
				}
			}
			weathermachine_cooler = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( -5, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/cs_office/vending_machine.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "weathermachine_cooler"
					origin = Vector( 72, 0.682922, 0 )
				}
			}
			weathermachine_fan = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_override"
					angles = Vector( 90, 90, 0 )
					damagetoenablemotion = "0"
					Damagetype = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					health = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props/de_inferno/ceiling_fan_blade.mdl"
					nodamageforces = "0"
					physdamagescale = "0.1"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "256"
					targetname = "weathermachine_fan"
					origin = Vector( 73, -36.2616, 31 )
				}
			}
			weathermachine_motor = 
			{
				SpawnInfo =
				{
					classname = "phys_motor"
					attach1 = "weathermachine_fan"
					axis = Vector( 73, -42.32, 31 )
					inertiafactor = "1.0"
					spawnflags = "6"
					speed = "1000"
					spinup = "5"
					targetname = "weathermachine_motor"
					origin = Vector( 73, -31.3171, 31 )
				}
			}
			weathermachine_fanbase = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 90, 90, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/de_inferno/ceiling_fan.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "weathermachine_fanbase"
					origin = Vector( 72.8945, -17.3171, 31 )
				}
			}
			weathermachine_block = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 75, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_highway/corrugated_panel_01.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "weathermachine_block"
					origin = Vector( 19, 28, 33 )
				}
			}
			weathermachine_steam2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 90, 180 )
					effect_name = "steam_short"
					targetname = "weathermachine_steam2"
					origin = Vector( 76, 19, 16 )
				}
			}
			weathermachine_steam1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -15, 255, 0 )
					effect_name = "steam_short"
					targetname = "weathermachine_steam1"
					origin = Vector( 37, -26, 37 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // DiescraperWeathermachine

RegisterEntityGroup( "DiescraperWeathermachine", DiescraperWeathermachine )
