//-------------------------------------------------------
// Autogenerated from 'gunhunt_item_spawn.vmf' and modified
//-------------------------------------------------------
RandomspawnerItemSpawn <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.randomspawner_item_spawn_target,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			randomspawner_item_spawn_target = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					targetname = "randomspawner_item_spawn"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // RandomspawnerItemSpawn

RegisterEntityGroup( "RandomspawnerItemSpawn", RandomspawnerItemSpawn )
